### PR TITLE
fixup powsybl110, single-line-diagram should be 2.10

### PR DESCRIPTION
**Pull request by jonenst**
Signed-off-by: HARPER Jon <jon.harper87@gmail.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
NO

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
bugfix

**What is the current behavior?** *(You can also link to an open issue here)*
powsybl-single-line-diagram.version 2.9.1

**What is the new behavior (if this is a feature change)?**
powsybl-single-line-diagram.version 2.10.0
NO

### CODE REVIEW

**Comment by geofjamg** [comment]
@jonenst Why you don't use powsybl dependencies?????

**Comment by geofjamg** [comment]
> @jonenst Why you don't use powsybl dependencies?????

It was supposed to be used also in powsybl web services (and maybe it was the place it was the most necessary because no gridsuite dependencies...)

**Comment by jonenst** [comment]
Yeah I wanted to first do the upgrade, and then use the new powsybl-dependencies, to do it step by step

**Comment by geofjamg** [comment]
> Yeah I wanted to first do the upgrade, and then use the new powsybl-dependencies, to do it step by step

But it would has avoid this bug to do it first...

**Review by FranckLecuyer — APPROVED** [review]

**Pull request merged**
